service: ping-my-sites

provider:
  name: aws
  runtime: nodejs10.x

functions:
  wake:
    handler: handler.wake
    events:
      - schedule:
        rate: cron(0,20，40 * * * *)
        enabled: true
    timeout: 20
